config/routes.rb
CoffeeShop::Application.routes.draw do
  


  resources :histories


  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'admin' => 'admin#index', as: :admin
  match 'admin/settings' => 'admin#settings', as: :admin_settings
  match 'admin/update_settings' => 'admin#update_settings', as: :admin_update_settings, via: :post
  match 'store' => 'store#index', as: :store
  match 'add_money' => 'users#add_money', as: :add_money
  match 'replenish' => 'products#replenish', as: :replenish
  match 'users/update_balance' => 'users#update_balance', as: :update_balance
  match 'users/edit_me' => 'users#edit_me', as: :edit_me
  match 'products/replenish' => 'products#update_stock', as: :update_stock
  match 'cleanings/howto' => 'cleanings#howto', as: :cleaning_howto
  match 'ask_pin' => 'user_sessions#ask_pin', as: :ask_pin
  match 'verify' => 'user_sessions#verify', as: :verify
  match 'checkout' => 'carts#checkout', as: :checkout
  match 'invoice' => 'carts#invoice', as: :invoice

  resources :cleanings


  resources :orders


  resources :usergroups
  

  resources :users


  resources :items_in_carts


  resources :carts 


  get "store/index"

  resources :products

  resources :user_sessions

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
  #root to: 'store#index', as: 'store'
  root to: 'user_sessions#new', as: 'root'
  # See how all your routes lay out with "rake routes"
end

app/views/admin/index.html.erb
<% content_for :head do %>
	<%= button_to 'Back', store_path, class: "bg-color-blue" %>
	Administration
<% end %>

<div class="grid">
  <div class="row">   

  	<% unless Product.stock_full? %>
  		<div class="admin_tile tile double bg-color-red">
      	<%= link_to products_path do %>
	      	<div class="tile_content">
						<div class="name">Products are running low!</div>
						<div style="font-size: x-small;">Click to see</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    	</div>
    <% end %>


    <div class="admin_tile tile">
      	<%= link_to :add_money do %>
	      	<div class="tile_content">
						<div class="name">Add Money</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

    <div class="admin_tile tile">
      	<%= link_to :replenish do %>
	      	<div class="tile_content">
						<div class="name">Replenish Stock</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

    <div class="admin_tile tile">
      	<%= link_to new_user_path do %>
	      	<div class="tile_content">
						<div class="name">Add User</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

    <div class="admin_tile tile">
      	<%= link_to new_product_path do %>
	      	<div class="tile_content">
						<div class="name">Add Product</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

    <div class="admin_tile tile">
      	<%= link_to new_cleaning_path do %>
	      	<div class="tile_content">
						<div class="name">Add Manual Cleaning</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>
  </div>

  <div class="row">   

     <div class="admin_tile tile">
      	<%= link_to admin_settings_path do %>
	      	<div class="tile_content">
						<div class="name">Settings</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

		<div class="admin_tile tile">
			<%= link_to products_path do %>
      	<div class="tile_content">
					<div class="name">Products</div>
				</div>
				<div class="brand"></div>
			<% end %>  
    </div>

    <div class="admin_tile tile">
      	<%= link_to users_path do %>
	      	<div class="tile_content">
						<div class="name">Users</div>
						<% if @debt != 0 %>
							<div class="info">Outstanding payments: <span class="bold"><%= number_to_currency @debt %></span></div>
						<% end %>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

    <div class="admin_tile tile">
      	<%= link_to histories_path do %>
	      	<div class="tile_content">
						<div class="name">History</div>
					</div>
					<div class="brand"></div>
				<% end %>      
    </div>

  </div>
</div>

app/views/admin/settings.html.erb
<% content_for :head do %>
	<%= button_to 'Back', admin_path %>
	Administrative Settings
<% end %>

<div>Coffes since last cleaning: <%= @counter %></div>

<%= form_tag("/admin/update_settings") do %>
  <% @settings.each do |key, val| %>
    <%= label_tag key.gsub(/_|\.|gui/, ' ') %><br />
	  <% if is_numeric(val) %>
	  	<%= input_nbr "field input-control text", key, val, "" %>
	  <% else %>
	  	<div class="field input-control text">
	  		<%= text_field_tag key, val %>
	  	</div>
	  <% end %>
  <% end %>
  <%= submit_tag("Save") %>
<% end %>