config/routes.rb
CoffeeShop::Application.routes.draw do
  


  resources :histories


  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'admin' => 'admin#index', as: :admin
  match 'admin/settings' => 'admin#settings', as: :admin_settings
  match 'admin/update_settings' => 'admin#update_settings', as: :admin_update_settings, via: :post
  match 'store' => 'store#index', as: :store
  match 'add_money' => 'users#add_money', as: :add_money
  match 'replenish' => 'products#replenish', as: :replenish
  match 'users/update_balance' => 'users#update_balance', as: :update_balance
  match 'users/edit_me' => 'users#edit_me', as: :edit_me
  match 'products/replenish' => 'products#update_stock', as: :update_stock
  match 'cleanings/howto' => 'cleanings#howto', as: :cleaning_howto
  match 'ask_pin' => 'user_sessions#ask_pin', as: :ask_pin
  match 'verify' => 'user_sessions#verify', as: :verify
  match 'checkout' => 'carts#checkout', as: :checkout
  match 'invoice' => 'carts#invoice', as: :invoice

  resources :cleanings


  resources :orders


  resources :usergroups
  

  resources :users


  resources :items_in_carts


  resources :carts 


  get "store/index"

  resources :products

  resources :user_sessions

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
  #root to: 'store#index', as: 'store'
  root to: 'user_sessions#new', as: 'root'
  # See how all your routes lay out with "rake routes"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :password_confirmation, :crypted_password, :email, :failed_login_count, :last_login_at, :last_request_at, :level, :login, :login_count, :password_salt, :persistence_token, :emptypw, :balance
  has_many :histories, :dependent => :delete_all

  validates :password, :password_confirmation, numericality: { only_integer: true, allow_blank: true }
  validates :level, presence: true

  acts_as_authentic do |config|
  	config.merge_validates_length_of_password_field_options minimum:4
  end
  
  def self.outstanding_payments
  	amount = 0
  	User.where("balance < 0").each {|u| amount += u.balance}
  	return -amount
  end

  def pay(cart)
  	ret = {bonus_points_used: 0, money_saved: 0, to_pay: 0, products: []}
  	cart.items_in_cart.each do | item |  		
    	quantity_to_pay = item.quantity
    	if item.product.name == "Coffee"
    		diff = item.quantity - self.bonus_points
    		if diff >= 0
    			quantity_to_pay = diff
    			self.bonus_points = 0
    		else
    			quantity_to_pay = 0
    			self.bonus_points = -diff
    		end
    		ret[:bonus_points_used] += item.quantity - quantity_to_pay
    		ret[:money_saved] += ret[:bonus_points_used] * item.product.price
    	end
    	
    	item.product.reduce_stock_by item.quantity
    	ret[:to_pay] += item.product.price * quantity_to_pay
    	
    	#add to history
    	self.histories << History.new(user_id: self.id, category: "buy", name: item.product.name, quantity: item.quantity, total: -(item.product.price * quantity_to_pay), bonus_points_used: (item.quantity - quantity_to_pay))
			ret[:products] << {name: item.product.name, quantity: item.quantity, price: item.product.price} 	
    end

    self.balance -= ret[:to_pay]  
    return ret
  end
  
  
  def add_balance_change_to_history(change)
  	cat = "pay-out"
  	cat = "deposit" if change >= 0
  	self.histories << History.new(user_id: self.id, category: cat, name: cat, quantity: 1, total: change)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_admin, except: [:show, :edit, :edit_me, :update ]
  before_filter :authorize 

    
  LEVELS = %w( Admin User )

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate page: params[:page], order: "login ASC"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @histories = History.where(user_id: @user.id).paginate(page: params[:page], per_page: 5).order("created_at DESC")

    #check if user is either admin or he is just looking on his own profile
    if_current_user_or_admin(@user.id) do
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def edit_me
    @user = User.find(current_user.id)
    @histories = History.where(user_id: @user.id).paginate(page: params[:page], per_page: 5).order("created_at DESC")
  end

  # GET /users/add_money
  def add_money
    @users = User.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.login} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    #check whether the pw is empty to work around authlogic
    if params[:user][:password] == ''
      @user.emptypw = true
    else
      @user.emptypw = false
    end

    #filter attributes not set-able by normal users
    unless is_admin
      params[:user].delete(:level);
      params[:user].delete(:balance);
    end    
    old_balance = @user.balance

    respond_to do |format|
      if @user.update_attributes(params[:user])
      	@user.add_balance_change_to_history(params[:user][:balance].to_f - old_balance) unless params[:user][:balance].blank?
        format.html { redirect_to user_url(@user.id) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_balance
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attribute(:balance, @user.balance + params[:balance].to_f)
      	@user.add_balance_change_to_history(params[:balance].to_f)
      
        format.html { redirect_to admin_url, notice: "Updated balance for #{@user.login}: #{view_context.number_to_currency(@user.balance)}" }
        format.json { head :no_content }
      else
        format.html { redirect_to admin_url, alert: "Could not update balance" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User #{@user.login} was successfully removed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def bonus_points_used(hist)
		return "(with #{hist.bonus_points_used} Bonus Points)" if hist.category == "buy"
		return ""
	end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
   <%= render partial: 'layouts/form_input_errors', object: @user.errors %>
  <% end %>

  <div class="field input-control text">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>

  <div class="field input-control text">
    <%= f.label :balance %><br />
    <%= input_nbr "field input-control text", "user[balance]", @user.balance, "€" %>
  </div>

  <div class="field input-control text">
    <%= f.label :level %><br />
    <%= f.select :level, UsersController::LEVELS, {:prompt => 'Select level'} %>
  </div>

  <div class="field input-control text">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field input-control password pin-field">
    <%= f.label "Pin" %><br />
    <%= f.password_field :password, class: "keyboard" %>
  </div>
  <div class="field input-control password pin-field">
    <%= f.label "Confirm Pin" %><br />
    <%= f.password_field :password_confirmation, class: "keyboard" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/add_money.html.erb
<% content_for :head do %>
	<%= button_to 'Back', admin_path, method: :get %>
	Add Money
<% end %>

<%= form_tag(:update_balance) do %>
	<div class="field input-control select">
		<select id="add_money_for" name="id">
			<%= options_from_collection_for_select @users, :id, :login %>
		</select>
	</div>
	<%= label_tag "Amount to add" %>
	<%= input_nbr "field input-control text", "balance", 10, "€" %>

	<div class="field input-control text">
		<input type="submit" value="Add" id="add_money" >
	</div>
<% end %>

app/views/users/edit.html.erb
<%= content_for :head do %>
	<%= button_to 'Back', user_path(@user.id), method: :get %>
	New user
<% end %>

<%= render 'form' %>

app/views/users/edit_me.html.erb
<% content_for :head do %>
	<%= button_to 'Back', store_path, method: :get %>
	Edit <%= @user.login %>'s details
<% end %>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
   <%= render partial: 'layouts/form_input_errors', object: @user.errors %>
  <% end %>

  <div class="field input-control text">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>

  <div class="field input-control text">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field input-control password pin-field">
    <%= f.label "Pin" %><br />
    <%= f.password_field :password, class: "keyboard" %>
  </div>
  <div class="field input-control password pin-field">
    <%= f.label "Confirm Pin" %><br />
    <%= f.password_field :password_confirmation, class: "keyboard" %>
  </div>
  <div class="field input-control ">
  	<%= f.label "Don't use Pin for login" %>
  	<%= f.check_box :emptypw %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render 'histories/list_history_linkless', object: @histories %>

app/views/users/index.html.erb
<% content_for :head do %>
	<%= button_to 'Back', :admin, method: :get %>
	Users
<% end %>

<table>
  <tr>
    <th>Login</th>
    <th>Level</th>
    <th>Email</th>
    <th>Balance</th>
  </tr>
    <% @users.each do |user| %>
      <tr data-link="<%= user_path(user.id) %>">
        <td><%= user.login %></td>
        <td><%= user.level %></td>
        <td><%= user.email %></td>
        <td><%= number_to_currency(user.balance) %></td>
      </tr>
    <% end %>
</table>
<%= will_paginate @users %>
<%= page_entries_info @users %>

<br />

<%= button_to 'New User', new_user_path, method: :get %>

app/views/users/new.html.erb
<%= content_for :head do %>
	<%= button_to 'Back', :back, method: :get %>
	New user
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :head do %>
  <% if is_admin %>
    <%= button_to 'Back', users_path, method: :get %>
  <% else %>
    <%= button_to 'Back', store_path, method: :get %>
  <% end %>
  <%= @user.login %>'s details
<% end %>

<p>
  <b>Login:</b>
  <%= @user.login %>
</p>

<p>
  <b>Balance:</b>
  <%= number_to_currency(@user.balance) %>
</p>

<p>
  <b>Bonus Points:</b>
  <%= @user.bonus_points %>
</p>

<p>
  <b>Level:</b>
  <%= @user.level %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Login count:</b>
  <%= @user.login_count %>
</p>

<p>
  <b>Failed login count:</b>
  <%= @user.failed_login_count %>
</p>

<%= render 'histories/list_history_linkless', object: @histories %>

<%= button_to 'Edit', edit_user_path(@user), method: :get %>
<% if is_admin %>
  <%= button_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>