config/routes.rb
CoffeeShop::Application.routes.draw do
  


  resources :histories


  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'admin' => 'admin#index', as: :admin
  match 'admin/settings' => 'admin#settings', as: :admin_settings
  match 'admin/update_settings' => 'admin#update_settings', as: :admin_update_settings, via: :post
  match 'store' => 'store#index', as: :store
  match 'add_money' => 'users#add_money', as: :add_money
  match 'replenish' => 'products#replenish', as: :replenish
  match 'users/update_balance' => 'users#update_balance', as: :update_balance
  match 'users/edit_me' => 'users#edit_me', as: :edit_me
  match 'products/replenish' => 'products#update_stock', as: :update_stock
  match 'cleanings/howto' => 'cleanings#howto', as: :cleaning_howto
  match 'ask_pin' => 'user_sessions#ask_pin', as: :ask_pin
  match 'verify' => 'user_sessions#verify', as: :verify
  match 'checkout' => 'carts#checkout', as: :checkout
  match 'invoice' => 'carts#invoice', as: :invoice

  resources :cleanings


  resources :orders


  resources :usergroups
  

  resources :users


  resources :items_in_carts


  resources :carts 


  get "store/index"

  resources :products

  resources :user_sessions

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
  #root to: 'store#index', as: 'store'
  root to: 'user_sessions#new', as: 'root'
  # See how all your routes lay out with "rake routes"
end

app/models/cleaning.rb
class Cleaning < ActiveRecord::Base
  attr_accessible :user_id

  validates :user_id, presence: true
end

app/controllers/cleanings_controller.rb
class CleaningsController < ApplicationController
  before_filter :authorize_admin, :except => [ :howto, :create ]
  before_filter :authorize

  def howto

  end

  # GET /cleanings
  # GET /cleanings.json
  def index
    @cleanings = Cleaning.paginate page: params[:page], order: "created_at DESC"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cleanings }
    end
  end

  # GET /cleanings/1
  # GET /cleanings/1.json
  def show
    @cleaning = Cleaning.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cleaning }
    end
  end

  # GET /cleanings/new
  # GET /cleanings/new.json
  # def new
  #   @cleaning = Cleaning.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @cleaning }
  #   end
  # end

  def new
    @users = User.all
  end

  # POST /cleanings
  # POST /cleanings.json
  def create
    unless params[:id].blank?
      user = User.find(params[:id])
    else
      user = current_user
    end
    @cleaning = Cleaning.new({ user_id: user.id })
    user.bonus_points += Settings['gui.points_for_cleaning'].to_i 
    user.save

    Settings.coffees_since_last_clean_up = 0

    respond_to do |format|
      if @cleaning.save
        format.html { redirect_to store_url, notice: "Thank you for cleaning!" }
        format.json { render json: @cleaning, status: :created, location: @cleaning }
      else
        format.html { render action: "new" }
        format.json { render json: @cleaning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cleanings/1
  # DELETE /cleanings/1.json
  def destroy
    @cleaning = Cleaning.find(params[:id])
    @cleaning.destroy

    respond_to do |format|
      format.html { redirect_to cleanings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cleanings_helper.rb
module CleaningsHelper
end

app/views/cleanings/_form.html.erb
<%= form_for(@cleaning) do |f| %>
  <% if @cleaning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cleaning.errors.count, "error") %> prohibited this cleaning from being saved:</h2>

      <ul>
      <% @cleaning.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cleanings/howto.html.erb
<% content_for :head do %>
  <%= button_to 'Back', store_path, method: :get %>
  How to clean
<% end %>
<ul>
	<li>		
			Step 1		
	</li>

	<li>		
			Step 2
	</li>

	<li>
			Step 3
	</li>

	<li>		
			Step 4
	</li>

	<li>		
			Step 5
	</li>
</ul>

<%= button_to 'All done', cleanings_path %>

app/views/cleanings/index.html.erb
<h1>Listing cleanings</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cleanings.each do |cleaning| %>
  <tr>
    <td><%= cleaning.user_id %></td>
    <td><%= link_to 'Show', cleaning %></td>
    <td><%= link_to 'Edit', edit_cleaning_path(cleaning) %></td>
    <td><%= link_to 'Destroy', cleaning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @cleanings %>

<%= link_to 'New Cleaning', new_cleaning_path %>

app/views/cleanings/new.html.erb
<% content_for :head do %>
	<%= button_to 'Back', admin_path, method: :get %>
	Add Manual Cleaning
<% end %>

<%= form_tag(cleanings_path) do %>
	<div class="field input-control select">
		<label>Who cleaned the machine?</label><br />
		<select id="add_cleaning_for" name="id">
			<%= options_from_collection_for_select @users, :id, :login %>
		</select>
	</div>

	<div class="field input-control text">
		<input type="submit" value="Add" id="add_money" >
	</div>
<% end %>

app/views/cleanings/show.html.erb
<p>
  <b>User:</b>
  <%= @cleaning.user_id %>
</p>


<%= link_to 'Edit', edit_cleaning_path(@cleaning) %> |
<%= link_to 'Back', cleanings_path %>