config/routes.rb
CoffeeShop::Application.routes.draw do
  


  resources :histories


  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'admin' => 'admin#index', as: :admin
  match 'admin/settings' => 'admin#settings', as: :admin_settings
  match 'admin/update_settings' => 'admin#update_settings', as: :admin_update_settings, via: :post
  match 'store' => 'store#index', as: :store
  match 'add_money' => 'users#add_money', as: :add_money
  match 'replenish' => 'products#replenish', as: :replenish
  match 'users/update_balance' => 'users#update_balance', as: :update_balance
  match 'users/edit_me' => 'users#edit_me', as: :edit_me
  match 'products/replenish' => 'products#update_stock', as: :update_stock
  match 'cleanings/howto' => 'cleanings#howto', as: :cleaning_howto
  match 'ask_pin' => 'user_sessions#ask_pin', as: :ask_pin
  match 'verify' => 'user_sessions#verify', as: :verify
  match 'checkout' => 'carts#checkout', as: :checkout
  match 'invoice' => 'carts#invoice', as: :invoice

  resources :cleanings


  resources :orders


  resources :usergroups
  

  resources :users


  resources :items_in_carts


  resources :carts 


  get "store/index"

  resources :products

  resources :user_sessions

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'
  #root to: 'store#index', as: 'store'
  root to: 'user_sessions#new', as: 'root'
  # See how all your routes lay out with "rake routes"
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :categorie, :description, :name, :price, :picture, :threshold, :in_stock, :amount_per_unit
  # multiple carts can contain the same product
  has_many :items_in_cart

  validates :name, :price, :in_stock, :threshold, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0} 
  validates :in_stock, :threshold, numericality: { only_integer: true, greater_than_or_equal_to: 0}
  validates :name, uniqueness: true
  # prevent the deletion of an product which is already in a cart
  before_destroy :ensure_not_referenced_by_any_items_in_cart

  # are there any items in a cart that reference this product?
  def ensure_not_referenced_by_any_items_in_cart
  	if items_in_cart.empty?
  		return true
  	else
  		errors.add(:base, 'Product still in a Cart')
  		return false
  	end
  end

  def reduce_stock_by(quantity)
    update_attribute(:in_stock, in_stock - quantity)
  end

  def is_running_low?
    in_stock <= threshold
  end

  def self.stock_full?
    Product.all.each { |product|
      if product.is_running_low?
        return false
      end
    }
    true
  end
  
  def self.price_of_coffee
  	return (Product.find_by_name "Coffee").price
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_filter :authorize_admin

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate page: params[:page], order: "name ASC"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  def replenish
    @products = Product.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_stock
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attribute(:in_stock, @product.in_stock + params[:stock].to_f)
        format.html { redirect_to admin_url, notice: "Replenished stock for #{@product.name}: #{@product.in_stock} Units available" }
        format.json { head :no_content }
      else
        format.html { redirect_to admin_url, alert: "Could not replenish" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end    
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <%= render partial: 'layouts/form_input_errors', object: @product.errors %>
  <% end %>

  <div class="field input-control text">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field input-control text">
    <%= f.label :price %><br />
    <%= input_nbr "field input-control text", "product[price]", @product.price, "€" %>
  </div>
  <div class="field input-control text">
    <%= f.label :amount_per_unit %><br />
      <%= input_nbr "field input-control text", "product[amount_per_unit]", @product.amount_per_unit %>
    <span>(e.g.: a cup of coffee needs 20g of coffee powder)</span>
  </div>
  <div class="field input-control text">
    <%= f.label :in_stock %><br />
      <%= input_nbr "field input-control text", "product[in_stock]", @product.in_stock %>
  </div>  
  <div class="field input-control text">
    <%= f.label :threshold %><br />
    <%= input_nbr "field input-control text", "product[threshold]", @product.threshold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= content_for :head do %>
	<%= button_to 'Back', products_path, method: :get, class: "bg-color-blue" %>
	Editing <%= @product.name %>
<% end %>

<%= render 'form' %>

app/views/products/index.html.erb
<% content_for :head do %>
    <%= button_to 'Back', :admin, method: :get %>
  Products
<% end %>

<% unless Product.stock_full? %>
  <%= render partial: 'layouts/notice', object: {head: "Products are running low", text: "They are marked below!"} %>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>In Stock</th>
  </tr>

<% @products.each do |product| %>
  <%= content_tag :tr, data: {link: product_path(product.id)}, class: (product.is_running_low? ? "bg-color-red" : "") do %>
    <td><%= product.name %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= product.in_stock %></td>
  <% end %>
<% end %>
</table>
<%= will_paginate @products %>

<br />

<%= button_to 'New Product', new_product_path, method: :get %>

app/views/products/new.html.erb
<%= content_for :head do %>
	<%= button_to 'Back', :back, method: :get %>
	New Product
<% end %>

<%= render 'form' %>

app/views/products/replenish.html.erb
<% content_for :head do %>
	<%= button_to 'Back', admin_path, method: :get %>
	Add to Stock
<% end %>

<%= form_tag(:update_stock) do %>
	<div class="field input-control select">
		<select id="replenish_stock_for" name="id">
			<%= options_from_collection_for_select @products, :id, :name %>
		</select>
	</div>
	<%= label_tag "Amount to add" %>
	<%= input_nbr "field input-control text", "stock" %>

	<div class="field input-control text">
		<input type="submit" value="Add" id="replenish" >
	</div>
<% end %>

app/views/products/show.html.erb
<% content_for :head do %>
  <%= button_to 'Back', products_path, method: :get%>
  <%= @product.name %>
<% end %>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@product.price) %>
</p>

<% if @product.is_running_low? %>
  <%= render partial: 'layouts/notice', object: { head: "Running low on #{@product.name}!"} %>
<% end %>

<p>
  <b>In Stock:</b>
  <%= @product.in_stock %>
</p>

<p>
  <b>Amount per Unit:</b>
  <%= @product.amount_per_unit %>
  <span>(e.g.: a cup of coffee needs 20g of coffee powder)</span>
</p>

<p>
  <b>Threshold:</b>
  <%= @product.threshold %>
</p>


<%= button_to 'Edit', edit_product_path(@product), method: :get %>
<%= button_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %>